from enum import StrEnum

from core.api_model import ApiModel


class ErrorCode(StrEnum):
    ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED"
    AUTH_ERROR = "AUTH_ERROR"
    BLOCKED = "BLOCKED"
    CANNOT_BLOCK_SELF = "CANNOT_BLOCK_SELF"
    CANNOT_LIKE_SELF = "CANNOT_LIKE_SELF"
    CANNOT_REPORT_SELF = "CANNOT_REPORT_SELF"
    CANNOT_VISIT_SELF = "CANNOT_VISIT_SELF"
    CHAT_BLOCKED = "CHAT_BLOCKED"
    CHAT_NOT_CONNECTED = "CHAT_NOT_CONNECTED"
    CHAT_USER_NOT_FOUND = "CHAT_USER_NOT_FOUND"
    DISCOVERY_ERROR = "DISCOVERY_ERROR"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_FILTER = "INVALID_FILTER"
    INVALID_LOCATION = "INVALID_LOCATION"
    INVALID_PHOTO_TYPE = "INVALID_PHOTO_TYPE"
    INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN"
    LOCATION_REQUIRED = "LOCATION_REQUIRED"
    MAX_FIVE_PHOTOS = "MAX_FIVE_PHOTOS"
    MISSING_TOKEN = "MISSING_TOKEN"
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    NO_PASSWORD_SET = "NO_PASSWORD_SET"
    OAUTH_ACCOUNT_CONFLICT = "OAUTH_ACCOUNT_CONFLICT"
    OAUTH_EXCHANGE_FAILED = "OAUTH_EXCHANGE_FAILED"
    PROFILE_PHOTO_REQUIRED = "PROFILE_PHOTO_REQUIRED"
    SOCIAL_ERROR = "SOCIAL_ERROR"
    TAGS_ERROR = "TAGS_ERROR"
    TAG_CONTENT_PROFANITY = "TAG_CONTENT_PROFANITY"
    TARGET_USER_NOT_FOUND = "TARGET_USER_NOT_FOUND"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    USERS_ERROR = "USERS_ERROR"
    USER_NOT_FOUND = "USER_NOT_FOUND"


class ErrorResponse(ApiModel):
    detail: str
    code: ErrorCode
    field: str | None = None


class ValidationIssue(ApiModel):
    loc: list[str | int]
    msg: str
    type: str


class ValidationErrorResponse(ApiModel):
    detail: list[ValidationIssue]
